name: CI-CD

on:
  workflow_dispatch:
  
  push:
    branches: 
      - devel
    paths:
      - rdicidr-0.1.0/**



jobs:
  CI:
    runs-on: ubuntu-latest
    
    defaults:
      run: 
        working-directory: rdicidr-0.1.0
        
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]        

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: "Install dependencies"
        run: npm install            
      
      - name: "Lint"
        run: npm run lint   
      
      - name: "Prettier"
        run: npm run prettier   
        
      - name: "Test (Jest)"
        run: CI=true npm run test       
        
      - name: "Build"
        run: npm run build       

      # Upload the artifact for other stages to use
      - name: Share artifact in github workflow
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: rdicidr-0.1.0/build/       
  CD:
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
      
      - name: "Build folder"
        run: ls -la build      

      - name: "Deploy application"
        run: echo "Deploy teste!"
